---
language: go
install:
- cd $TRAVIS_BUILD_DIR && make build
- go test -i ./...
script: cd $TRAVIS_BUILD_DIR && make test
notifications:
  email:
    recipients:
      - flintknappers+amqp-tools@modcloth.com
